[[anim]]
name = "LeftCellAnim"
file = "assets/cell/cell.aseprite"
default = "Yy"

[anim.variants.Never]
no_stutter = true

[[anim]]
name = "RightCellAnim"
file = "assets/cell/cell.aseprite"
default = "Yy"

[anim.variants.None]
no_stutter = true

[[anim]]
name = "SpikeAnim"
file = "assets/cell/cell.aseprite"
default = "Spikes"

[anim.variants.Spikes]
no_stutter = true
